// <auto-generated />
using System;
using KaryawanAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaryawanAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120004824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KaryawanAPI.Models.Karyawan", b =>
                {
                    b.Property<string>("NIK")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Negara")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("datetime(6)");

                    b.HasKey("NIK");

                    b.ToTable("Karyawans");
                });
#pragma warning restore 612, 618
        }
    }
}
